version: '3.2'
services:
  grpc-server:
    build: .
    expose:
      - 50051
    command: python route_guide_server.py
  nginx:
    build: ./nginx
    ports:
      - 50021:50021
      #- 443:443
  grpc-client:
    build: .
    command: bash -c 'sleep 3 && python route_guide_client.py'
